### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by jim-rosales** [jane548/colmar_academy#5]
Grade: Exceeds Expectations

Summary:
Excellent job on your capstone project! I liked the several hover effects you added to the page. You also did a fine job commenting, and structuring your code. 

My only recommendation is to keep in mind that hover effects won't be noticed by mobile users since they make use of the mouse. 

For extra practice try making the menu sticky or fixed to the top! I'm sure you've seen this feature before on other websites.

**Comment by jane548** [comment]
Thanks for your review Jim! All the best!

-Ashton
